/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HandleRouteImport } from './routes/$handle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandleBackupRouteImport } from './routes/$handle.backup'

const HandleRoute = HandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleBackupRoute = HandleBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => HandleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRouteWithChildren
  '/$handle/backup': typeof HandleBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRouteWithChildren
  '/$handle/backup': typeof HandleBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$handle': typeof HandleRouteWithChildren
  '/$handle/backup': typeof HandleBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$handle' | '/$handle/backup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$handle' | '/$handle/backup'
  id: '__root__' | '/' | '/$handle' | '/$handle/backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandleRoute: typeof HandleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$handle': {
      id: '/$handle'
      path: '/$handle'
      fullPath: '/$handle'
      preLoaderRoute: typeof HandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle/backup': {
      id: '/$handle/backup'
      path: '/backup'
      fullPath: '/$handle/backup'
      preLoaderRoute: typeof HandleBackupRouteImport
      parentRoute: typeof HandleRoute
    }
  }
}

interface HandleRouteChildren {
  HandleBackupRoute: typeof HandleBackupRoute
}

const HandleRouteChildren: HandleRouteChildren = {
  HandleBackupRoute: HandleBackupRoute,
}

const HandleRouteWithChildren =
  HandleRoute._addFileChildren(HandleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandleRoute: HandleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
